version: '2.1'
services:
  main:
    image: sahil87/polr:v1.1
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    environment:
      - APP_ADDRESS=localhost
    depends_on:
      mysql:
        condition: service_healthy
      myadmin:
        condition: service_started

  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=polr
      - MYSQL_PASSWORD=polr
      - MYSQL_DATABASE=polr
    healthcheck:
      test: ["CMD-SHELL", "test `echo 'SELECT 1' | mysql -hmysql -upolr -ppolr --silent` = '1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - PMA_ABSOLUTE_URI=http://localhost:8080
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=secret
